# BLUE
BG_COLOR = "#F2EFE7"
BTN_SELECTED_COLOR = "#9ACBD0"
BTN_COLOR = "#48A6A7"
BTN_TEXT_COLOR = "#FFFFFF"
TEXT_COLOR = "#2973B2"

# PINK+PURPLE
# BG_COLOR = "#F8E7F6"
# BTN_SELECTED_COLOR = "#FCC6FF"
# BTN_COLOR = "#DD88CF"
# BTN_TEXT_COLOR = "#FFFFFF"
# TEXT_COLOR = "#4B164C"

# PLUM
# BG_COLOR = "#FBFBFB"
# BTN_SELECTED_COLOR = "#C890A7"
# BTN_COLOR = "#A35C7A"
# BTN_TEXT_COLOR = "#FFFFFF"
# TEXT_COLOR = "#441752"

# GREEN+PURPLE
# BG_COLOR = "#F9F6E6"
# BTN_SELECTED_COLOR = "#E1EACD"
# BTN_COLOR = "#BAD8B6"
# BTN_TEXT_COLOR = "#FFFFFF"
# TEXT_COLOR = "#8D77AB"